title:            Go Go Go
description:      Programming
url:              # Site url.
signoff:          # Your name.
disqus_shortname: ldsgh
facebook_appid:   # appid for like button, remove from /_includes/share.html if unwanted.
google_analytics: # set tracking, remove from /javascripts/basic.js if unwanted.

links:
  - name:         About
    url:          /about
  - name:         Blog
    url:          http://lidashuang.github.io
    external:     true
  - name:         Email
    url:          mailto:ldshuang@gmail.cog
    external:     true
  - name:         GitHub
    url:          http://github.com/lidashuang
    external:     true
highlighter:      pygments
permalink:        pretty
markdown:         redcarpet
redcarpet:
  extensions:
    - smart
